# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('progress', models.PositiveSmallIntegerField()),
                ('posted', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('progress', models.PositiveSmallIntegerField()),
                ('processstep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preingest.ProcessStep')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
