# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20160830_1023'),
        ('ip', '0003_auto_20160823_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpackage',
            name='SubmissionAgreement',
        ),
        migrations.AddField(
            model_name='informationpackage',
            name='SA',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.SubmissionAgreement'),
        ),
    ]
