# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0004_auto_20160830_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationpackage',
            old_name='SA',
            new_name='SubmissionAgreement',
        ),
    ]
